### PR TITLE
feat(doc): Nominate SIG Chairs and Technical Leads

### PR DESCRIPTION
**Pull request by leonrayang**
According to pull request :https://github.com/cubefs/cubefs/pull/3430, sigs need chairs and tecnical leads to garantee the evething runs normally

### CODE REVIEW

**Comment by leonrayang** [comment]
+1

**Review by Cloudstriff — APPROVED** [review]
+1

**Comment by Victor1319** [comment]
+1

**Review by xiaochunhe — APPROVED** [review]
+1，LGTM

**Review by awzhgw — APPROVED** [review]
+1

**Comment by hooklee2000** [comment]
+1

**Review by bladehliu — APPROVED** [review]
+1

**Review by shuoranliu — APPROVED** [review]

**Review by heymingwei — APPROVED** [review]

**Review by sejust — APPROVED** [review]

**Comment by sejust** [comment]
+1

**Pull request merged**
